repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    args: [--safe, --quiet]
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    language_version: python3
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.4.0
  hooks:
  - id: reorder-python-imports
    args: ["--application-directories=.:src"]
