---
version: "2.4"

volumes:

  # Internal named volumes.
  # These are not accessible outside of the docker host and are maintained by
  # Docker.
  mysql_data:
  archivematica_storage_service_staging_data:

  # External named volumes.
  # These are intended to be accessible beyond the docker host (e.g. via NFS).
  # They use bind mounts to mount a specific "local" directory on the docker
  # host - the expectation being that these directories are actually mounted
  # filesystems from elsewhere.
  archivematica_pipeline_data:
    external:
      name: "am-pipeline-data"
  archivematica_storage_service_location_data:
    external:
      name: "ss-location-data"


services:

  mysql:
    image: "percona:5.6"
    user: "mysql"
    command: "--character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "127.0.0.1:62001:3306"

  redis:
    image: "redis:3.2-alpine"
    command: '--save "" --appendonly no'  # Persistency disabled
    user: "redis"
    ports:
      - "127.0.0.1:62003:6379"

  gearmand:
    image: "artefactual/gearmand:1.1.17-alpine"
    command: "--queue-type=redis --redis-server=redis --redis-port=6379"
    user: "gearman"
    ports:
      - "127.0.0.1:62004:4730"
    links:
      - "redis"

  archivematica-mcp-server:
    build:
      context: "."
      target: "archivematica-mcp-server"
      args:
        TARGET: "archivematica-mcp-server"
    environment:
      A3M_DB_USER: "archivematica"
      A3M_DB_PASSWORD: "demo"
      A3M_DB_HOST: "mysql"
      A3M_DB_DATABASE: "MCP"
      A3M_GEARMAN_SERVER: "gearmand:4730"
      A3M_PROMETHEUS_BIND_PORT: "7999"
      A3M_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
    volumes:
      - ".:/a3m"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"

  archivematica-mcp-client:
    build:
      context: "."
      target: "archivematica-mcp-client"
      args:
        TARGET: "archivematica-mcp-client"
    environment:
      A3M_DB_USER: "archivematica"
      A3M_DB_PASSWORD: "demo"
      A3M_DB_HOST: "mysql"
      A3M_DB_DATABASE: "MCP"
      A3M_GEARMAN_SERVER: "gearmand:4730"
      A3M_PROMETHEUS_BIND_PORT: "7999"
      A3M_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
      A3M_CLAMAV_CLIENT_MAX_FILE_SIZE: "42"
      A3M_CLAMAV_CLIENT_MAX_SCAN_SIZE: "42"
      A3M_CLAMAV_CLIENT_MAX_STREAM_LENGTH: "100"
      A3M_CLAMAV_CLIENT_BACKEND: "clamscan" # Option: clamdscanner or clamscan;
    volumes:
      - ".:/a3m"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"
      - "archivematica-storage-service"

  archivematica-storage-service:
    build:
      context: "./hack/modules/archivematica-storage-service"
    environment:
      FORWARDED_ALLOW_IPS: "*"
      SS_GUNICORN_ACCESSLOG: "/dev/null"
      SS_GUNICORN_RELOAD: "true"
      SS_GUNICORN_RELOAD_ENGINE: "auto"
      DJANGO_SETTINGS_MODULE: "storage_service.settings.local"
      SS_DB_URL: "mysql://archivematica:demo@mysql/SS"
      SS_GNUPG_HOME_PATH: "/var/archivematica/storage_service/.gnupg"
      SS_PROMETHEUS_ENABLED: "true"
    volumes:
      - "./hack/modules/archivematica-storage-service/:/src/"
      - "./hack/modules/archivematica-sampledata/:/home/archivematica/archivematica-sampledata/:ro"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - "archivematica_storage_service_staging_data:/var/archivematica/storage_service:rw"
      - "archivematica_storage_service_location_data:/home:rw"
    links:
      - "mysql"
