---
version: "2.4"

volumes:

  # Internal named volumes.
  # These are not accessible outside of the docker host and are maintained by
  # Docker.
  mysql_data:

  # External named volumes.
  # These are intended to be accessible beyond the docker host (e.g. via NFS).
  # They use bind mounts to mount a specific "local" directory on the docker
  # host - the expectation being that these directories are actually mounted
  # filesystems from elsewhere.
  archivematica_pipeline_data:
    external:
      name: "am-pipeline-data"

services:

  mysql:
    image: "percona:5.6"
    user: "mysql"
    command: "--character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "127.0.0.1:52001:3306"

  gearmand:
    image: "artefactual/gearmand:1.1.17-alpine"
    command: "--queue-type=builtin"
    user: "gearman"
    ports:
      - "127.0.0.1:52002:4730"

  archivematica-mcp-server:
    build:
      context: "."
      target: "archivematica-mcp-server"
      args:
        TARGET: "archivematica-mcp-server"
    environment:
      A3M_DB_USER: "archivematica"
      A3M_DB_PASSWORD: "demo"
      A3M_DB_HOST: "mysql"
      A3M_DB_DATABASE: "MCP"
      A3M_GEARMAN_SERVER: "gearmand:4730"
      A3M_PROMETHEUS_BIND_PORT: "7999"
      A3M_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
    volumes:
      - ".:/a3m"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"
    ports:
      - "127.0.0.1:52000:8000"

  archivematica-mcp-client:
    build:
      context: "."
      target: "archivematica-mcp-client"
      args:
        TARGET: "archivematica-mcp-client"
    environment:
      A3M_DB_USER: "archivematica"
      A3M_DB_PASSWORD: "demo"
      A3M_DB_HOST: "mysql"
      A3M_DB_DATABASE: "MCP"
      A3M_GEARMAN_SERVER: "gearmand:4730"
      A3M_PROMETHEUS_BIND_PORT: "7999"
      A3M_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
      A3M_CLAMAV_CLIENT_MAX_FILE_SIZE: "42"
      A3M_CLAMAV_CLIENT_MAX_SCAN_SIZE: "42"
      A3M_CLAMAV_CLIENT_MAX_STREAM_LENGTH: "100"
      A3M_CLAMAV_CLIENT_BACKEND: "clamscan" # Option: clamdscanner or clamscan;
    volumes:
      - ".:/a3m"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"
